spring:
  application:
    name: ms-students
  datasource:
    url: jdbc:postgresql://localhost:5432/students_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update